
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 26.1 and Phased Array System Toolbox 26.1

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',10,...
    'ArrayAxis','z');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = 0.5*0.6;
Array.Taper = ones(1,10).';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.FrequencyRange = [0 500000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 500000000;
PropagationSpeed = 300000000;

% Assign Steering Angles
SteeringAngles = [0;90];
% Assign Phase shift quantization bits
PhaseShiftBits = 0;

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormals',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Calculate Steering Weights

Freq3D = 500000000;
% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
SteerVector = phased.SteeringVector('SensorArray', Array,...
    'PropagationSpeed', PropagationSpeed, 'NumPhaseShifterBits', PhaseShiftBits(1));
for idx = 1:length(Frequency)
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end

% Plot 3d graph
format = 'polar';
plotType = 'Directivity';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w(:,1),...
    'ShowArray',false,'ShowLocalCoordinates',true,...
    'ShowColorbar',true,'Orientation',[0;0;0],...
    'Type', plotType);

% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(Frequency)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed, ...
        'NumPhaseShifterBits', PhaseShiftBits(idx));
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(Frequency)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed,...
        'NumPhaseShifterBits', PhaseShiftBits(idx));
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end

% Plot 2d elevation graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, cutAngle, -90:90, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(Frequency)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed,...
        'NumPhaseShifterBits', PhaseShiftBits(idx));
    w(:, idx) = step(SteerVector, Frequency(idx), SteeringAngles(:, idx));
end


% Plot U Pattern
format = 'uv';
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -1:0.01:1, 0, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Plot Grating Lobe Diagram
figure;
plotGratingLobeDiagram(Array,Frequency(1),SteeringAngles(:,1),PropagationSpeed);



%% Graficado de pesos 
%%Gráfica de los pesos calculados por el script (amplitud y fase) 
n_sensor = 0:(getNumElements(Array)-1);

figure;
subplot(2,1,1);
stem(n_sensor, abs(w(:,1)));
grid on;
xlabel('Índice de sensor n'); ylabel('Amplitud');
title('Amplitud del vector de pesos w');

subplot(2,1,2);
stem(n_sensor, rad2deg(angle(w(:,1))));
grid on;
xlabel('Índice de sensor n'); ylabel('Fase (grados)');
title('Fase del vector de pesos w');
