
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 26.1 and Phased Array System Toolbox 26.
% Create a uniform rectangular array
Array = phased.URA('Size',[4 4],...
    'Lattice','Rectangular','ArrayNormal','z');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = [0.5 0.5]*0.6;
% Calculate Row taper
rwind = ones(1,4).';
% Calculate Column taper
cwind = ones(1,4).';
% Calculate taper
taper = rwind*cwind.';
Array.Taper = taper.';

% Create an isotropic antenna element
Elem = phased.IsotropicAntennaElement;
Elem.FrequencyRange = [0 500000000];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 500000000;
PropagationSpeed = 300000000;

% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormals',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);
% Plot Array Geometry
pos = getElementPosition(Array);  % posiciones reales [x;y;z] de cada elemento

figure;
scatter3(pos(1,:), pos(2,:), pos(3,:), 100, 'filled', ...
    'MarkerFaceColor', [0 0.4470 0.7410]);
axis equal;
grid on;
xlabel('x (m)');
ylabel('y (m)');
zlabel('z (m)');
title('Array Planar Uniforme 4\times4, d = 0.5\lambda');
view(30,25);   % ajusta estos dos valores (azimut, elevación) a tu gusto

% Opcional: líneas guía para remarcar la rejilla
hold on;
for k = 1:size(pos,2)
    plot3([pos(1,k) pos(1,k)], [pos(2,k) pos(2,k)], [0 pos(3,k)], ...
        'Color', [0.7 0.7 0.7], 'LineStyle', ':');
end
hold off;
% Calculate Steering Weights

Freq3D = 500000000;
% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 3d graph
format = 'polar';
plotType = 'Directivity';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w(:,1),...
    'ShowArray',false,'ShowLocalCoordinates',true,...
    'ShowColorbar',true,'Orientation',[0;0;0],...
    'Type', plotType);


% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d elevation graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, cutAngle, -90:90, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot U Pattern
format = 'uv';
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -1:0.01:1, 0, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

